### ISSUE TITLE
Error response from daemon: oci runtime error: container_linux.go:247

### ISSUE THREAD

**Issue by moriweiji** [plippe/faiss-web-service#15]
[root@localhost opt]# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
docker.io/plippe/faiss-web-service   1.2.1-cpu           177ca41c46f0        9 hours ago         1.76 GB
docker.io/plippe/faiss-web-service   latest              177ca41c46f0        9 hours ago         1.76 GB
[root@localhost opt]# docker run --rm --detach --publish 5000:5000 plippe/faiss-web-service:1.2.1-cpu
2194a8c6c1a81b499dd89e012d59504b80e37230788a4536b60a143c80476e71
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/opt/faiss-web-service/bin/faiss_web_service.sh\": stat /opt/faiss-web-service/bin/faiss_web_service.sh: no such file or directory".

**Comment by plippe** [comment]
Hi,

Sorry about that. The bin folder was removed accidentally in a previous update. 
I updated the docker images, and it should work now. 

Sorry again
