### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by moriweiji** [plippe/faiss-web-service#17]
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED              STATUS              PORTS                    NAMES
f731d1c8ebe7        plippe/faiss-web-service:1.2.1-cpu   "/opt/faiss-web-se..."   About a minute ago   Up About a minute   0.0.0.0:5000->5000/tcp   focused_pare
[root@localhost ~]# curl 'localhost:5000/ping'
curl: (56) Recv failure: Connection reset by peer
[root@localhost ~]# curl '0.0.0.0:5000/ping'  
curl: (56) Recv failure: Connection reset by peer
[root@localhost ~]# curl 'localhost:5000/faiss/search' -X POST -d '{"k": 5, "ids": [1, 2, 3]}'
curl: (56) Recv failure: Connection reset by peer

**Comment by plippe** [comment]
Hi,

Really sorry for all the issues you are running into.

I have ran your commands, but I don't have the same results that you are having. 

First make sure you have the latest version of the docker image by stopping and removing your current containers and images.

After run the docker image in interactive mode to see the logs. Those will be needed if there is an error to fix.
```
pvinchon$ docker run --rm -itp 5000:5000 plippe/faiss-web-service:1.2.1-cpu
Unable to find image 'plippe/faiss-web-service:1.2.1-cpu' locally
1.2.1-cpu: Pulling from plippe/faiss-web-service
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
f48d20dabdb7: Pull complete
6ba01d80c8e2: Pull complete
a97934523920: Pull complete
25b70844e398: Pull complete
61a309d4d691: Pull complete
145881d8cd17: Pull complete
Digest: sha256:ad85c6a83aa3210ec983e8dec88ced0b2dd787833b0b00eeca12c94406cebaa3
Status: Downloaded newer image for plippe/faiss-web-service:1.2.1-cpu
Failed to load python module uwsgi
Periodic faiss index updates isn't enabled
Getting Faiss resources
Getting Faiss index
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Failed to load python module uwsgi
Periodic faiss index updates isn't enabled
Getting Faiss resources
Getting Faiss index
 * Debugger is active!
 * Debugger PIN: 329-691-435
```

The container takes a few minutes to start as it must download resources. Running requests during that time will give the following response:
```
pvinchon$ curl 0.0.0.0:5000/ping
curl: (52) Empty reply from server 
```

Once fully loaded, the server will start responding:
```
pvinchon$ curl 0.0.0.0:5000/ping
pong
```

I use `0.0.0.0` as my docker host url, but this could be different on your machine. You will need to look up online how to obtain that information on your operating system.

I hope this helps.

**Comment by plippe** [comment]
No further answer, closing issue
