### ISSUE TITLE
image feature is 2-Dimensional, what is ids for one picture ?

### ISSUE THREAD

**Issue by linzuk** [Plippe/faiss-web-service#2]
i extract feature from image. every picture have 2-Dimensional feature, like [[0.32, 0.52 ...], [0.32, 0.52 ...], [0.32, 0.52 ...]].
when i index for one picture. it like this 

xb = # xb extract from one image
index = faiss.IndexFlatL2(xb.shape[1])
index_with_ids = faiss.IndexIDMap(index)
index_with_ids.add_with_ids(xb, ids)

then, what is ids for one picture ?

and, what is xb and ids for many images ? (image feature is 2-Dimensional)

**Comment by linzuk** [comment]
does all the id for one picture xb is the same?
xb = # xb extract from one image
ids = [image_id] * xb.shape[0]   # all the id for this image is same
index = faiss.IndexFlatL2(xb.shape[1])
index_with_ids = faiss.IndexIDMap(index)
index_with_ids.add_with_ids(xb, ids)

**Comment by Plippe** [comment]
These questions are related to `faiss`, not this project. Please read their documentation:
- https://github.com/facebookresearch/faiss/wiki/Pre--and-post-processing#faiss-id-mapping
