### ISSUE TITLE
Unable to upgrade faiss

### ISSUE THREAD

**Issue by slash4** [plippe/faiss-web-service#24]
Hi ! Thanks for this very simple yet powerful tool !

Just wondering if someone here has managed to upgrade to faiss 1.5.2 ? When I try to do so, I struggle with endless conflicts within conda, and even when I manage to make it run, uwsgi is missing and screws up everything. In my last try I downgraded python to 3.6, thinking it was the problem (spoiler : it wasn't), and now I got `ImportError: cannot import name 'FaissIndex'`. Really don't get it.  

I'm starting a fresh new project with faiss, and I really want it to be up to date, there is no point starting today with an already outdated version. Hope someone can help :) Thanks for reading.

**Comment by plippe** [comment]
Hey,

I haven't worked on this project for quite some time (April 2018).
I don't have a solution for you, but I can look at updating Faiss to the latest version.

Hopefully, I should be able to do that over the weekend.

**Comment by slash4** [comment]
That would be : awesome :) Thanks for looking !

**Comment by slash4** [comment]
Just be aware that starting from version 1.5.3, faiss relies on new cpu instructions, that seems to be incompatible with my development machine. That's why I was sticking to 1.5.2.

**Comment by plippe** [comment]
Have you tried using the docker version?
It definitely won't be as fast but should work on most systems (Windows cough cough).

**Comment by slash4** [comment]
I don't understand :) Isn't faiss-web-service already based on docker ? Are you talking about github.com/facebookresearch/faiss ? Or maybe github.com/plippe/faiss-docker ?

Sorry, maybe dumb question :) But I don't see what you mean.

**Comment by plippe** [comment]
Sorry, could have been more explicit

Faiss-web-service can run outside of docker. This is often where people have issues. You can skip a few hurdles by using the Dockerized version. By your comment, it seems to be what you are trying to do.

Anyways, just updated [faiss-docker](https://github.com/plippe/faiss-docker) to use the latest non-broken Faiss release, [1.5.2](https://hub.docker.com/layers/plippe/faiss-docker/1.5.2/images/sha256-2e2360e308131c5421874bdaf353e10fa6db8691857538e550f3550980bea9f3). The versions 1.6.1, 1.6.0, and 1.5.3 fail building.

Starting work on the server.

**Comment by plippe** [comment]
All done

The new image can be downloaded with `docker pull plippe/faiss-web-service:1.5.2`
I removed most of the configuration and the uwsgi logic as it was unreliable 
The new way to load indexes is described in the README.md 

Hope that helps

**Comment by slash4** [comment]
Hello ! You rock. Thanks a lot. I'm closing this issue right now. 

Just one last question, you say in the readme that Flask clearly states it is not suited for production, so if we plan going to production with this solution, what should we do ? Trying to re-implement uwsgi, or an alternative solution ? Ditch docker and go native on a dedicated machine ?

**Comment by plippe** [comment]
The production code with wsgi wasn't really working. To avoid shipping this project with a broken production environment, I preferred to pull it out. 

Flask has a few suggestions on how to properly [deploy to production](https://flask.palletsprojects.com/en/1.1.x/tutorial/deploy/). When I have more time, I might give it another go. Until then, you have two options:
1. Ignore the warning, it should work for small projects 
2. Fork the repository and implement one of the [deployment methods](https://flask.palletsprojects.com/en/1.0.x/deploying/#deployment)

Good luck with your project

**Comment by slash4** [comment]
Very clear. Thanks again for your help. That's very appreciated !
