### ISSUE TITLE
Is there any image build in python3?

### ISSUE THREAD

**Issue by eshaoliu** [plippe/faiss-web-service#26]

**Comment by plippe** [comment]
Hi eshaoliu,

Thank you for your patience.

The base docker image is built from [the official faiss repository](https://github.com/facebookresearch/faiss) with the help of [the faiss-docker repository](https://github.com/plippe/faiss-docker). 

Facebook doesn't ship an image with python 3. I won't either.

**Comment by eshaoliu** [comment]
Thanks.
