### ISSUE TITLE
when run index script,i got the RuntimeError that 'nx >= k' failed

### ISSUE THREAD

**Issue by wongdu** [plippe/faiss-web-service#27]
after run the “python train_index.py” command, got the fellow error message:

  File "/root/anaconda3/envs/tempCv36/lib/python3.6/site-packages/faiss/__init__.py", line 157, in replacement_train
    self.train_c(n, swig_ptr(x))
  File "/root/anaconda3/envs/tempCv36/lib/python3.6/site-packages/faiss/swigfaiss_avx2.py", line 6097, in train
    return _swigfaiss_avx2.IndexIDMap_train(self, n, x)
RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at Clustering.cpp:273: Error: 'nx >= k' failed: Number of training points (796) should be at least as large as number of clusters (1024)

**Comment by wongdu** [comment]
the images are the reason?

**Comment by plippe** [comment]
Hi Wongdu,

I do not know, I haven't really touched this project nor Faiss for quite some time. 

Just a guess, the error message should help
> Error: 'nx >= k' failed: Number of training points (796) should be at least as large as number of clusters (1024)

Good luck

**Comment by wongdu** [comment]
plippe,thanks a lot 
with another images,the error message disappears, but donot know why. i will check it out later
