### ISSUE TITLE
reverse image search engine

### ISSUE THREAD

**Issue by batara666** [plippe/faiss-web-service#28]

**Comment by plippe** [comment]
Hi batara,

Your issue is currently light in details. Would you have any more you could share?

**Comment by batara666** [comment]
It is possible to build reverse image search engine with faiss ?

**Comment by plippe** [comment]
Yes you can.

I would encourage you to start with Faiss before looking at my web service. The official repository should have more documentation.

The gist is to convert images to vectors. That is the hardest step for accurate results. Then, store the vectors with their image identifier in Faiss. This will allow searches to return the identifiers/images that closely matches your query.

I hope this helps.
